name: Release

on:
  push:
    paths:
      - '.github/workflows/release.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 1.0.0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}